using System.Linq;
using Tools.ExternalDevServices.Integrations.GitHub;
using Tools.ExternalDevServices.Utils;

namespace Tools.ExternalDevServices.AI.Orchestration.Utils;

public static class PullRequestCommentUtils
{
    public const string AiGeneratedPullRequestOverviewCommentMarker = "<sub>(*AI Generated Pull Request Overview Comment*)</sub>";
    public const string AiGeneratedPullRequestFileCommentMarker = "<sub>(*AI Generated File Comment*)</sub>";
    public const string AiGeneratedPullRequestCodeCommentMarker = "<sub>(*AI Generated Code Comment*)</sub>";

    public const string AiGeneratedPullRequestOverviewCommentDisclaimer =
        """
        <sub>*This overview was generated by AI*; 
        while efforts have been made to ensure accuracy, authors and reviewers are encouraged to verify as it may not capture the purpose of the pull request correctly, may misinterpret change types, or may suggest a non-optimal review plan.</sub>
        """;
    public const string AiGeneratedPullRequestFileReviewCommentDisclaimer =
        """
        <sub>*This file comment was generated by AI; 
        while efforts have been made to ensure accuracy, authors and reviewers are encouraged to verify as it may be misleading, inaccurate, or unnecessary.*</sub>
        """;
    public const string AiGeneratedPullRequestCodeCommentDisclaimer =
        """
        <sub>*This code comment was generated by AI; 
        while efforts have been made to ensure accuracy, authors and reviewers are encouraged to verify as it may be misleading, inaccurate, or unnecessary.*</sub>
        """;

    public static bool HasCommentWithPrefix(PullRequestDetails pullRequestDetails, string prefix) => 
        pullRequestDetails.Comments.Any(c => c.Body.StartsWith(prefix, StringComparison.OrdinalIgnoreCase));

    public static async Task<(int commentId, string htmlUrl, bool added)> AddOrUpdateCommentWithPrefixMarkerAndPostfixToPullRequestAsync(
        GitHubRestApiClient gitHubRestApiClient, PullRequestDetails pullRequestDetails, bool postCommentAsReviewer, string comment, string prefix, string postfix, DiagnosticsHelper? diagnostics)
    {
        return postCommentAsReviewer? await AddOrUpdateReviewerCommentWithPrefixMarkerAndPostfixToPullRequestAsync(gitHubRestApiClient, pullRequestDetails, comment, prefix, postfix, diagnostics) :
            await AddOrUpdatePullRequestCommentWithPrefixMarkerAndPostfixToPullRequestAsync(gitHubRestApiClient, pullRequestDetails, comment, prefix, postfix, diagnostics);
    }

    private static async Task<(int commentId, string htmlUrl, bool added)> AddOrUpdateReviewerCommentWithPrefixMarkerAndPostfixToPullRequestAsync(GitHubRestApiClient gitHubRestApiClient, PullRequestDetails pullRequestDetails, string comment, string prefix, string postfix, DiagnosticsHelper? diagnostics)
    {
        var reviewer = (await gitHubRestApiClient.GetAuthenticatedUserAsync()).Login;

        var formattedComment = $"{prefix}\r\n\r\n{comment}\r\n\r\n{postfix}";

        // Find an existing review *by this reviewer* that matches our prefix marker
        var existingReview = pullRequestDetails.Reviews.FirstOrDefault(r =>
            r.Body.StartsWith(prefix, StringComparison.OrdinalIgnoreCase) &&
            string.Equals(r.User, reviewer, StringComparison.OrdinalIgnoreCase));

        (int commentId, string htmlUrl) reviewDetails;
        var added = false;

        if (existingReview is null)
        {
            diagnostics?.AddInformation("Reviewer comment not found, creating review (COMMENT)...");
            reviewDetails = await gitHubRestApiClient.AddReviewToPullRequestAsync(
                pullRequestDetails.Repo,
                pullRequestDetails.Number,
                formattedComment);

            added = true;
        }
        else
        {
            reviewDetails = (existingReview.Id, existingReview.HtmlUrl);
            diagnostics?.AddInformation($"Reviewer comment (review #{reviewDetails.commentId}) found, updating...");

            await gitHubRestApiClient.UpdateReviewAsync(
                pullRequestDetails.Repo,
                pullRequestDetails.Number,
                reviewDetails.commentId,
                formattedComment);

            var formattedReReviewComment = $"{prefix}\r\n\r\nRe-review completed\r\n\r\n{postfix}";
            await gitHubRestApiClient.AddReviewToPullRequestAsync(
                pullRequestDetails.Repo,
                pullRequestDetails.Number,
                formattedReReviewComment);
        }

        return (reviewDetails.commentId, reviewDetails.htmlUrl, added);
    }

    private static async Task<(int commentId, string htmlUrl, bool added)> AddOrUpdatePullRequestCommentWithPrefixMarkerAndPostfixToPullRequestAsync(GitHubRestApiClient gitHubRestApiClient, PullRequestDetails pullRequestDetails, string comment, string prefix, string postfix, DiagnosticsHelper? diagnostics)
    {
        var existingComment = pullRequestDetails.Comments.FirstOrDefault(c =>
            c.Body.StartsWith(prefix, StringComparison.OrdinalIgnoreCase));

        var formattedComment = $"{prefix}\r\n\r\n{comment}\r\n\r\n{postfix}";

        (int commentId, string htmlUrl) commentDetails;
        var added = false;
        if (existingComment is null)
        {
            diagnostics?.AddInformation("Comment not found, adding...");
            commentDetails =
                await gitHubRestApiClient.AddCommentToPullRequestAsync(pullRequestDetails.Repo, pullRequestDetails.Number, formattedComment);
            added = true;
        }
        else
        {
            commentDetails = (existingComment.Id, existingComment.HtmlUrl);
            diagnostics?.AddInformation($"Comment #{commentDetails.commentId} found, updating...");
            await gitHubRestApiClient.UpdateComment(pullRequestDetails.Repo, commentDetails.commentId, formattedComment);
        }

        return (commentDetails.commentId, commentDetails.htmlUrl, added);
    }
}