<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Tools.ExternalDevServices.AI.MCP.$(MSBuildProjectName)</AssemblyName>
    <RootNamespace>Tools.ExternalDevServices.AI.MCP.$(MSBuildProjectName.Replace(" ", "_").Replace("-", "_"))</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\McpUtils\McpUtils.csproj" />
  </ItemGroup>

</Project>
